
version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./db-data:/data/db
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file: .env
