openapi: 3.0.0
info:
  title: Chat API
  version: 1.0.0
paths:
  /api/history:
    get:
      summary: Fetch a list of sessions
      description: Returns an array of session objects
      responses:
        '200':
          description: Successful response
      